import {
  ApartmentAvailabilityStatus,
  ApartmentFinishingType,
  ApartmentSaleType,
  IApartmentProps,
} from "@pbb/models/apartments/IApartment";
import { connectMongo } from "../db/mongoose";
import Apartment from "@pbb/models/apartments/Apartment";
import { IApartmentAmenitiesProps } from "@pbb/models/apartmentAmenities/IApartmentAmenities";
import ApartmentAmenities from "@pbb/models/apartmentAmenities/ApartmentAmenities";
import { IDeveloperProps } from "@pbb/models/developers/IDeveloper";
import Developer from "@pbb/models/developers/Developer";

const sampleApartmentAmenIties: IApartmentAmenitiesProps[] = [
  {
    name: "Club House",
    icon: "https://prod-images.cooingestate.com/processed/amenity/image/19/medium.webp",
  },
  {
    name: "Underground parking",
    icon: "https://prod-images.cooingestate.com/processed/amenity/image/14/medium.webp",
  },
  {
    name: "Outdoor pools",
    icon: "https://prod-images.cooingestate.com/processed/amenity/image/7/medium.webp",
  },
];

const sampleDevelopers: IDeveloperProps[] = [
  {
    name: "Orascom",
  },
  {
    name: "TMG",
  },
];

export async function runApartmentSeed() {
  await connectMongo();
  const apartmentAmenItiesCount = await ApartmentAmenities.countDocuments();

  if (apartmentAmenItiesCount === 0) {
    await ApartmentAmenities.insertMany(sampleApartmentAmenIties);
    console.log("[Seed] Inserted sample apartment amenities");
  }

  const developersCount = await Developer.countDocuments();
  if (developersCount === 0) {
    await Developer.insertMany(sampleDevelopers);
    console.log("[Seed] Inserted sample developers");
  }

  const amenityDocs = await ApartmentAmenities.find({}, { _id: 1 }).lean();
  const amenityIds = amenityDocs.map((a) => a._id);

  const developers = await Developer.find({}, { _id: 1 }).lean();
  if (!developers.length) throw new Error("No developers found for seeding");
  const randomDevId =
    developers[Math.floor(Math.random() * developers.length)]._id;

  const count = await Apartment.countDocuments();
  if (count === 0) {
    const sampleApartments: IApartmentProps[] = [
      {
        unitName: "Nile View Studio",
        unitNumber: "A-101",
        referenceNumber: 100001,
        projectName: "Zed East",
        price: 2_200_000,
        bedrooms: 1,
        bathrooms: 1,
        areaSqm: 58,
        images: [
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83",
          "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        ],
        address: "Zed East, New Cairo",
        city: "New Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Cozy studio with partial Nile view.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 5,
        yearBuilt: 2022,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Garden Apartment",
        unitNumber: "B-204",
        referenceNumber: 100002,
        projectName: "Palm Hills October",
        price: 3_400_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 95,
        images: [
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83",
          "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
        ],
        address: "Palm Hills, 6th of October",
        city: "6th of October",
        country: "Egypt",
        amenities: amenityIds,
        description: "Ground floor unit with private garden.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 0,
        yearBuilt: 2019,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Penthouse Sky",
        unitNumber: "PH-01",
        referenceNumber: 100003,
        projectName: "Mivida",
        price: 6_200_000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqm: 180,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
          "https://images.unsplash.com/photo-1600585154526-990dced4db0d",
        ],
        address: "Mivida, New Cairo",
        city: "New Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Penthouse with large terrace and skyline view.",
        availabilityStatus: ApartmentAvailabilityStatus.RENTED,
        floor: 7,
        yearBuilt: 2021,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Parkside Two-Bed",
        unitNumber: "C-213",
        referenceNumber: 100004,
        projectName: "Mountain View iCity",
        price: 3_200_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 110,
        images: [
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83",
        ],
        address: "iCity, New Cairo",
        city: "New Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Overlooking the park, bright interiors.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 3,
        yearBuilt: 2020,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.NOT_FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Lakefront 3BR",
        unitNumber: "D-330",
        referenceNumber: 100005,
        projectName: "New Giza",
        price: 5_400_000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqm: 165,
        images: [
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
        ],
        address: "New Giza, Giza",
        city: "Giza",
        country: "Egypt",
        amenities: amenityIds,
        description: "Lake-facing apartment with wide balcony.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 4,
        yearBuilt: 2018,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Eastown Cozy 1BR",
        unitNumber: "E-118",
        referenceNumber: 100006,
        projectName: "Eastown",
        price: 2_600_000,
        bedrooms: 1,
        bathrooms: 1,
        areaSqm: 72,
        images: [
          "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
          "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83",
          "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        ],
        address: "Eastown, 90 Street",
        city: "New Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Cozy, walkable to retail spine.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 1,
        yearBuilt: 2020,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Villette Family 3BR",
        unitNumber: "V-405",
        referenceNumber: 100007,
        projectName: "Villette",
        price: 5_600_000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqm: 170,
        images: [
          "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&h=400&fit=crop",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop",
          "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=600&h=400&fit=crop",
          "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&h=400&fit=crop",
        ],
        address: "Villette, New Cairo",
        city: "New Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Family layout with clubhouse access.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 2,
        yearBuilt: 2021,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.NOT_FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "SODIC East Corner 2BR",
        unitNumber: "S-221",
        referenceNumber: 100008,
        projectName: "SODIC East",
        price: 3_800_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 120,
        images: [
          "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&h=400&fit=crop",
          "https://images.unsplash.com/photo-1560448205-17d3a46c84de?w=600&h=400&fit=crop",
          "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=600&h=400&fit=crop",
          "https://images.unsplash.com/photo-1560448205-97d3a46c84de?w=600&h=400&fit=crop",
        ],
        address: "SODIC East, New Heliopolis",
        city: "New Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Corner unit near community center.",
        availabilityStatus: ApartmentAvailabilityStatus.OFF_MARKET,
        floor: 2,
        yearBuilt: 2022,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.NOT_FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Marassi Chalet",
        unitNumber: "M-9-12",
        referenceNumber: 100009,
        projectName: "Marassi",
        price: 7_500_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 105,
        images: [
          "https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=700&h=500&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&h=500&fit=crop",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=700&h=500&fit=crop",
          "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=700&h=500&fit=crop",
        ],
        address: "Marassi, North Coast",
        city: "North Coast",
        country: "Egypt",
        amenities: amenityIds,
        description: "Beach access chalet, furnished.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 1,
        yearBuilt: 2020,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Hacienda White Villa Annex",
        unitNumber: "H-3-07",
        referenceNumber: 100010,
        projectName: "Hacienda White",
        price: 9_100_000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqm: 190,
        images: [
          "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&h=500&fit=crop",
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        ],
        address: "Hacienda White, Km 140",
        city: "North Coast",
        country: "Egypt",
        amenities: amenityIds,
        description: "Annex with private garden and pool access.",
        availabilityStatus: ApartmentAvailabilityStatus.RENTED,
        floor: 0,
        yearBuilt: 2019,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Alamein Towers Sea View",
        unitNumber: "AT-1802",
        referenceNumber: 100011,
        projectName: "Alamein Towers",
        price: 12_000_000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqm: 200,
        images: [
          "https://images.unsplash.com/photo-1501183638710-841dd1904471",
        ],
        address: "New Alamein Downtown",
        city: "New Alamein",
        country: "Egypt",
        amenities: amenityIds,
        description: "High-floor tower apartment with sea view.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 18,
        yearBuilt: 2023,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Porto Sokhna Terrace",
        unitNumber: "PS-5C",
        referenceNumber: 100012,
        projectName: "Porto Sokhna",
        price: 2_100_000,
        bedrooms: 1,
        bathrooms: 1,
        areaSqm: 70,
        images: [
          "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde",
        ],
        address: "Ain Sokhna, Km 55",
        city: "Ain Sokhna",
        country: "Egypt",
        amenities: amenityIds,
        description: "Sea-view terrace unit.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 5,
        yearBuilt: 2018,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Zamalek Classic 2BR",
        unitNumber: "Z-602",
        referenceNumber: 100013,
        projectName: "Zamalek Residences",
        price: 4_300_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 145,
        images: [
          "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
        ],
        address: "Zamalek, Cairo",
        city: "Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Classic layout with river proximity.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 6,
        yearBuilt: 2018,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Heliopolis Sunlit 1BR",
        unitNumber: "H-217",
        referenceNumber: 100014,
        projectName: "Heliopolis Gardens",
        price: 2_400_000,
        bedrooms: 1,
        bathrooms: 1,
        areaSqm: 80,
        images: [
          "https://images.unsplash.com/photo-1486304873000-235643847519",
        ],
        address: "Heliopolis, Cairo",
        city: "Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Sunlit apartment near services.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 2,
        yearBuilt: 2020,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.NOT_FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Nasr City Budget 2BR",
        unitNumber: "N-044",
        referenceNumber: 100015,
        projectName: "Nasr City Heights",
        price: 1_800_000,
        bedrooms: 2,
        bathrooms: 1,
        areaSqm: 95,
        images: [
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
        ],
        address: "Nasr City, Cairo",
        city: "Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Budget-friendly with solid layout.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 4,
        yearBuilt: 2019,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.NOT_FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Sheikh Zayed Loft",
        unitNumber: "SZ-1203",
        referenceNumber: 100016,
        projectName: "Beverly Hills",
        price: 4_100_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 130,
        images: [
          "https://images.unsplash.com/photo-1564013799919-ab600027ffc6",
        ],
        address: "Beverly Hills, Sheikh Zayed",
        city: "Sheikh Zayed",
        country: "Egypt",
        amenities: amenityIds,
        description: "Loft-style with double-height living.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 12,
        yearBuilt: 2021,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Maadi Tree View",
        unitNumber: "MD-403",
        referenceNumber: 100017,
        projectName: "Maadi Degla",
        price: 3_600_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 125,
        images: [
          "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        ],
        address: "Maadi Degla",
        city: "Cairo",
        country: "Egypt",
        amenities: amenityIds,
        description: "Green view, quiet street.",
        availabilityStatus: ApartmentAvailabilityStatus.RENTED,
        floor: 4,
        yearBuilt: 2018,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "New Capital Smart Home",
        unitNumber: "NC-702",
        referenceNumber: 100018,
        projectName: "Capital Residence",
        price: 4_700_000,
        bedrooms: 3,
        bathrooms: 2,
        areaSqm: 155,
        images: [
          "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5",
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        ],
        address: "R7, New Capital",
        city: "New Capital",
        country: "Egypt",
        amenities: amenityIds,
        description: "Smart-home enabled corner unit.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 7,
        yearBuilt: 2023,
        saleType: ApartmentSaleType.DEVELOPER_SALE,
        finishingType: ApartmentFinishingType.NOT_FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Alexandria Corniche",
        unitNumber: "AX-1504",
        referenceNumber: 100019,
        projectName: "San Stefano",
        price: 6_800_000,
        bedrooms: 3,
        bathrooms: 3,
        areaSqm: 175,
        images: [
          "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        ],
        address: "San Stefano, Alexandria",
        city: "Alexandria",
        country: "Egypt",
        amenities: amenityIds,
        description: "Sea-line living on the Corniche.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 15,
        yearBuilt: 2019,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
      {
        unitName: "Gouna Lagoon 2BR",
        unitNumber: "EG-7A",
        referenceNumber: 100020,
        projectName: "El Gouna",
        price: 5_200_000,
        bedrooms: 2,
        bathrooms: 2,
        areaSqm: 135,
        images: [
          "https://images.unsplash.com/photo-1501045661006-fcebe0257c3f",
          "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
          "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
        ],
        address: "Lagoon-side, El Gouna",
        city: "Red Sea",
        country: "Egypt",
        amenities: amenityIds,
        description: "Lagoon view with private dock access nearby.",
        availabilityStatus: ApartmentAvailabilityStatus.AVAILABLE,
        floor: 2,
        yearBuilt: 2022,
        saleType: ApartmentSaleType.RESALE,
        finishingType: ApartmentFinishingType.FINISHED,
        developer: randomDevId,
      },
    ];
    await Apartment.insertMany(sampleApartments);
    console.log("[Seed] Inserted sample apartments");
  } else {
    console.log("[Seed] Skipped, collection not empty");
  }
}
